const express = require('express')
const router = express.Router()
const AuthRouter = require('./application/auth.route')
const UserRouter = require('./user/users.route')
const CategoryRouter = require('./category/category.route')
const BusinessRouter = require('./business/business.route')
const BusinessReviewRouter = require('./business/business-review.route')
const DropdownRouter = require('./common/dropdown.route')
const MediaRouter = require('./application/media.route')
const HomeSliderRouter = require('./application/home-slider.route')
const PersonRouter = require('./application/person.route')
const PricingPackageRouter = require('./application/pricing-package.route')
const EventRouter = require('./event/event.route')
const NewsRouter = require('./news/news.route')
const FileRouter = require('./application/file.route')
const OpeningHourRouter = require('./application/opening-hours.route')
const UIRouter = require('./application/ui.route')
const DataManagementRouter = require('./data-management/data-management.route')

/* GET home page. */
router.get('/get-csv', function (req, res, next) {
  res.status(200).write('EXPRESS')
})

router.use('/auth', AuthRouter)
router.use('/users', UserRouter)
router.use('/category', CategoryRouter)
router.use('/business', BusinessRouter)
router.use('/business-review', BusinessReviewRouter)
router.use('/dropdown', DropdownRouter)
router.use('/media', MediaRouter)
router.use('/home-slider', HomeSliderRouter)
router.use('/contact-person', PersonRouter)
router.use('/pricing-package', PricingPackageRouter)
router.use('/event', EventRouter)
router.use('/news', NewsRouter)
router.use('/file', FileRouter)
router.use('/opening-hours', OpeningHourRouter)
router.use('/ui', UIRouter)
router.use('/data-management', DataManagementRouter)

module.exports = router
